FROM golang:1.23.4-bookworm AS builder

WORKDIR /src

COPY go.mod go.sum ./
COPY vendor ./vendor
RUN go mod verify

COPY cmd ./cmd
COPY service ./service
COPY webui ./webui

RUN CGO_ENABLED=1 go build -trimpath -ldflags="-s -w" -o /app/webapi ./cmd/webapi
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /app/healthcheck ./cmd/healthcheck

FROM debian:bookworm-20241202-slim

WORKDIR /app

RUN groupadd --system --gid 10001 wasatext \
    && useradd --system --uid 10001 --gid wasatext --home-dir /app wasatext \
    && mkdir -p /data \
    && chown wasatext:wasatext /data

COPY --from=builder /app/webapi ./
COPY --from=builder /app/healthcheck ./

HEALTHCHECK --interval=30s --timeout=5s --start-period=5s --retries=3 CMD ["/app/healthcheck"]

EXPOSE 3000

USER 10001:10001

CMD ["/app/webapi"]
