version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wasa-text-backend
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: wasa-text-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
