FROM golang:latest AS builder

WORKDIR /src

COPY . .

RUN go build -o /app/webapi ./cmd/webapi

FROM debian:bookworm

WORKDIR /app

COPY --from=builder /app/webapi ./

EXPOSE 3000

CMD ["/app/webapi"]
