FROM node:lts AS builder

WORKDIR /src/webui

RUN corepack enable && corepack prepare yarn@1.22.22 --activate

COPY webui/package.json webui/yarn.lock ./

RUN yarn install --frozen-lockfile

COPY webui/ ./

RUN yarn build --mode production

FROM nginx:alpine

COPY --from=builder /src/webui/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]