openapi: 3.0.0
info:
  title: WASAText
  description: |
    This OpenAPI document describes APIs for WASAText project.

    Studente: Francesco Zompanti
    Matricola: 2012601
    e-mail: zompanti.2012601@studenti.uniroma1.it
  version: 0.0.1

tags:
  - name: login
    description: Endpoints for user authentication and session creation
  - name: user
    description: Endpoints for managing user profiles and personal settings
  - name: conversation
    description: Endpoints for retrieving and managing user conversations
  - name: message
    description: Endpoints for sending, forwarding and deleting messages
  - name: comment
    description: Endpoints for adding and removing reactions or comments on messages
  - name: group
    description: Endpoints for creating, updating and managing group chats

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: string
  
security:
  - BearerAuth: []

paths:
  /session:
    post:
      tags:
        - login
      summary: Logs in the user
      description: |
        If the user doesn't exist, it will be created and returned an identifier.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      security: []
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '201':
          description: User login action successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                identifier: "abcdef012345"
  /users/photo:
    get:
      tags:
        - user
      summary: Retrieves the authenticated user's photo
      description: Returns the full User object
      operationId: getMyPhoto
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User photo fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: "justchecco"
                name: "Francesco"
                photo: "aGPsaG8="
    put:
      tags:
        - user
      summary: Updates the authenticated user's photo
      description: Updates the user's photo and returns the updated User object
      operationId: setMyPhoto
      security:
        - BearerAuth: []
      requestBody:
        description: New photo (JPEG or PNG) as a base64-encoded string
        required: true
        content:
          image/png:
            schema:
              type: string
              description: PNG image file
              pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
              minLength: 1
              maxLength: 10485760
          image/jpeg:
            schema:
              type: string
              description: JPEG image file
              pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
              minLength: 1
              maxLength: 10485760
      responses:
        '200':
          description: Photo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: "justchecco"
                name: "Francesco"
                photo: "aGPsaG8="
    /users/name:
      put:
        tags:
          - user
        summary: Updates the authenticated user's username
        description: Updates the user's username
        operationId: setMyUsername
        security:
          - BearerAuth: []
        requestBody:
          description: New username
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserRequest'
        responses:
          '200':
            description: Username updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/User'
                example:
                  id: "justchecco"
                  name: "Francesco"
                  photo: "aGPsaG8="
          