openapi: 3.0.0
info:
  title: WASAText
  description: |
    This OpenAPI document describes APIs for WASAText project.

    Studente: Francesco Zompanti
    Matricola: 2012601
    e-mail: zompanti.2012601@studenti.uniroma1.it
  version: 0.0.1

tags:
  - name: login
    description: Endpoints for user authentication and session creation
  - name: user
    description: Endpoints for managing user profiles and personal settings
  - name: conversation
    description: Endpoints for retrieving and managing user conversations
  - name: message
    description: Endpoints for sending, forwarding and deleting messages
  - name: comment
    description: Endpoints for adding and removing reactions or comments on messages
  - name: group
    description: Endpoints for creating, updating and managing group chats

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: string
  
security:
  - bearerAuth: []

paths:
  /session:
    post:
      tags:
        - login
      summary: Logs in the user
      description: |
        If the user doesn't exist, it will be created and returned an identifier.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      security: []
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '201':
          description: User login action successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                identifier: "abcdef012345"
      